version: "3"
services:
  openvpn-as:
    image: linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - INTERFACE=eth0 #optional
    volumes:
      - openvpn-as:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    networks:
      - bridge
    restart: unless-stopped
volumes:
    openvpn-as:
    
